version: '3'
services:
  system_function:
    build:
      context: ./system-function
      dockerfile: Dockerfile
    ports:
      - "1111:80"
  ssti:
    build:
      context: ./SSTI
      dockerfile: Dockerfile
    ports:
      - "2222:5000"
  file_upload:
    build:
      context: ./file-upload
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./file-upload/app
        target: /var/www/html
    ports:
      - "3333:80"
  deserializatoin:
    build:
      context: ./deserialization
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
  # bonus:
  #   build:
  #     context: ./bonus-challenge
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5555:80"

